### ISSUE TITLE
[cpackget] regression issue with 0.9.2

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#772]
Hi

I got a regression using the new cpackget version.

```
$ cpackget.exe -V
cpackget version 0.9.0 (C) 2022 Linaro

$ cpackget.exe add STMicroelectronics.stm32u5xx_hal_drivers.2.0.0-alpha.1.1
I: Using pack root: "xxx\cmsis_pack_root"
I: Adding pack "STMicroelectronics.stm32u5xx_hal_drivers.2.0.0-alpha.1.1"
I: Extracting files to xxx\cmsis_pack_root\STMicroelectronics\stm32u5xx_hal_drivers\2.0.0-alpha.1.1...
```

I am now using the latest version:
```
$ cpackget.exe -V
cpackget version 0.9.2 (C) 2022-2023 Linaro

$ cpackget.exe add STMicroelectronics.stm32u5xx_hal_drivers.2.0.0-alpha.1.1
I: Using pack root: "xxx\cmsis_pack_root"
I: Adding pack "STMicroelectronics.stm32u5xx_hal_drivers.2.0.0-alpha.1.1"
I: Extracting files to xxx\cmsis_pack_root\STMicroelectronics\stm32u5xx_hal_drivers\2.0.0-alpha.1.1...
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/open-cmsis-pack/cpackget/cmd/installer.(*PacksInstallationType).PackIsInstalled(0xc00017b500, 0xc0001e0410)
        /home/runner/work/cpackget/cpackget/cmd/installer/root.go:959 +0x1159
github.com/open-cmsis-pack/cpackget/cmd/installer.(*PackType).loadDependencies(0xc0001e0750)
        /home/runner/work/cpackget/cpackget/cmd/installer/pack.go:573 +0x23d
github.com/open-cmsis-pack/cpackget/cmd/installer.AddPack({0xc000028480?, 0x38?}, 0x1, 0x0, 0x0, 0x0, 0x0?)
        /home/runner/work/cpackget/cpackget/cmd/installer/root.go:158 +0xadf
github.com/open-cmsis-pack/cpackget/cmd/commands.glob..func1(0x1a85a40?, {0xc000064e10?, 0x1?, 0x1?})
        /home/runner/work/cpackget/cpackget/cmd/commands/add.go:96 +0x571
github.com/spf13/cobra.(*Command).execute(0x1a85a40, {0xc000064de0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x1aa5a40?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 +0x19
main.main()
        /home/runner/work/cpackget/cpackget/cmd/main.go:24 +0xca
```

**Comment by jkrech** [comment]
I have raised an issue labeled "bug" in the cpackget repository and close the issue here.
